Refactor dataset download process for efficiency, simplicity, and security
PrimeIntellect-ai/prime-diloco pull request #115
Opened 2024-10-16 03:11 UTC by Nottlespike

- Replace Git LFS dependency with custom Python script
- Utilize aria2c/wget for faster, multi-threaded downloads
- Implement data rank-based subset selection
- Streamline setup process and reduce dependencies
- Update README with new download instructions
- Fixed issue with ~/10B/H100.toml where it would attempt to access the root /data/ directory

This change improves download speeds, reduces system requirements,
and simplifies the dataset preparation workflow for users.

NOTE: The data rank-based subset selection logic should be verified
by maintainers to ensure it matches the intended implementation.

2024-10-16 03:19 UTC, samsja commented on configs/10B/H100.toml
> -dataset_name_or_paths = "/data/datasets/fineweb-edu,/data/datasets/fineweb,/data/datasets/StackV1-popular,/data/datasets/dclm-baseline-1.0-parquet,/data/datasets/open-web-math"
we still want to keep the `/data/` as this is where we store our data for the 10b run

2024-10-16 03:24 UTC, Nottlespike commented on configs/10B/H100.toml
> -dataset_name_or_paths = "/data/datasets/fineweb-edu,/data/datasets/fineweb,/data/datasets/StackV1-popular,/data/datasets/dclm-baseline-1.0-parquet,/data/datasets/open-web-math"
I mean that works but is not ideal. You use the root /data directory? This requires you to run the script as sudo or be a root user. We can symlink to be backwards compatible but using the root /data is certainly a bad practice in my thoughts.

2024-10-16 03:31 UTC, Nottlespike commented on configs/10B/H100.toml
> -dataset_name_or_paths = "/data/datasets/fineweb-edu,/data/datasets/fineweb,/data/datasets/StackV1-popular,/data/datasets/dclm-baseline-1.0-parquet,/data/datasets/open-web-math"
Perhaps we should have a migration script? If we MUST keep it as is I can modify the PR to accomodate, but it would require the user to run the dataset script as sudo.

2024-10-16 04:05 UTC, samsja commented on configs/10B/H100.toml
> -dataset_name_or_paths = "/data/datasets/fineweb-edu,/data/datasets/fineweb,/data/datasets/StackV1-popular,/data/datasets/dclm-baseline-1.0-parquet,/data/datasets/open-web-math"
We are mainly using the 10b config for us right now, let's keep it like this. user can override it and we can fix it later

2024-10-16 04:17 UTC, Nottlespike commented on configs/10B/H100.toml
> -dataset_name_or_paths = "/data/datasets/fineweb-edu,/data/datasets/fineweb,/data/datasets/StackV1-popular,/data/datasets/dclm-baseline-1.0-parquet,/data/datasets/open-web-math"
> We are mainly using the 10b config for us right now, let's keep it like this. user can override it and we can fix it later

Yeah this would be a breaking change to the 10B run right now. Perhaps we could move this to a branch and merge it after the 10B is trained?

2024-10-16 04:38 UTC, samsja commented on configs/10B/H100.toml
> -dataset_name_or_paths = "/data/datasets/fineweb-edu,/data/datasets/fineweb,/data/datasets/StackV1-popular,/data/datasets/dclm-baseline-1.0-parquet,/data/datasets/open-web-math"
yeah could makes sense :smile:

2024-10-16 20:09 UTC, Jackmin801 approved these changes
Nice! Thanks for the PR :) Added some minor comments.
Ill give it a spin on my side to make sure its working and we should be able to merge without the changes to `H100.toml`

2024-10-16 20:09 UTC, Jackmin801 commented on scripts/subset_data.py
> +    return [f for f in all_files if f.endswith('.parquet')]
Nice solution. This gets every file in the dataset regardless of the dataset config though.
What do you think about using datasets BuilderConfig to retrieve datafiles? It would support dataset configs and be closest to how the HF dataset would parse the data files.

2024-10-16 20:09 UTC, Jackmin801 commented on README.md
> +  --dataset_name PrimeIntellect/fineweb-edu,PrimeIntellect/fineweb,PrimeIntellect/StackV1-popular,PrimeIntellect/dclm-baseline-1.0-parquet,PrimeIntellect/open-web-math \
Lets change the dclm and openwebmath org to their respective orgs so `mlfoundations/dclm-baseline-1.0-parquet`, `open-web-math/open-web-math`.

We dont have dclm-baseline-1.0-parquet and open-web-math on PrimeIntellect atm because we didn't need to reshuffle them (they seemed shuffled enough, though maybe we could have reshuffled them to be sure and also to get nicer shard sizes).

2024-10-16 20:09 UTC, Jackmin801 requested changes
Ah accidentally approved

2024-10-16 23:41 UTC, Nottlespike commented on README.md
> +  --dataset_name PrimeIntellect/fineweb-edu,PrimeIntellect/fineweb,PrimeIntellect/StackV1-popular,PrimeIntellect/dclm-baseline-1.0-parquet,PrimeIntellect/open-web-math \
Ah I see. I should have checked for all the respositories.

2024-10-17 00:20 UTC, Nottlespike commented on scripts/subset_data.py
> +    return [f for f in all_files if f.endswith('.parquet')]
That would be a more robust solution that is closer to how the Hugging Face datasets library parses the data. It would require some small changes in data.py to handle this. I can modify the PR.

2024-10-17 01:48 UTC, Nottlespike commented on scripts/subset_data.py
> +    return [f for f in all_files if f.endswith('.parquet')]
Ok this is tougher than expected but necessary. Will likely have to rewrite to hande dataset configs.

2024-10-17 20:38 UTC, closed without merging