PRI-442: Implement HTTPMonitor to send node status and training progress
PrimeIntellect-ai/prime-diloco pull request #17
Opened 2024-09-28 20:54 UTC by manveerxyz

- Utilize existing Monitor abstraction to send node/training progress to our Prime Protocol API
- Merging into POC branch for now

2024-09-28 22:50 UTC, samsja commented on configs/150M/3090.toml
> +base_url = "https://protocol-api.primeintellect.ai"
lets not add them to the config for now

2024-09-28 22:51 UTC, samsja commented on configs/debug/diloco.toml
> +type = "dummy"
you can override this with cli

2024-09-28 22:54 UTC, samsja commented on src/zeroband/utils/monitor.py
> +        self.batch_size = getattr(config.progress_logger, 'batch_size', 10)
not sure about the default value to 10

2024-09-28 22:55 UTC, samsja commented on src/zeroband/utils/monitor.py
> +        self._remove_duplicates()
there seems to be two call to `_remove_duplicates` here

2024-09-29 17:26 UTC, manveerxyz commented on src/zeroband/utils/monitor.py
> +        self.batch_size = getattr(config.progress_logger, 'batch_size', 10)
what do you think it should be?

2024-10-01 16:09 UTC, samsja commented on pyproject.toml
> +    "einops",
einops should stay in the main dependency

2024-10-01 16:10 UTC, samsja approved these changes
PR looks ,good I am wondering how we could use wandb + our monitor at the same time

2024-10-01 16:17 UTC, samsja requested changes
seems that tests are not passing for me locally with this pr `tests/test_configs.py:7: in <module>
    from zeroband.train import Config
src/zeroband/train.py:25: in <module>
    from zeroband.utils.monitor import WandbMonitor, DummyMonitor, HttpMonitor
src/zeroband/utils/monitor.py:6: in <module>
    logger = get_logger()
src/zeroband/utils/logging.py:32: in get_logger
    world_info = get_world_info()
src/zeroband/utils/world_info.py:28: in get_world_info
    world_info = WorldInfo()
src/zeroband/utils/world_info.py:15: in __init__
    self.world_size = int(os.environ["WORLD_SIZE"])
../../../.pyenv/versions/3.10.13/lib/python3.10/os.py:680: in __getitem__
    raise KeyError(key) from None
E   KeyError: 'WORLD_SIZE'
========================================================================================== short test summary info ==========================================================================================
ERROR tests/test_configs.py - KeyError: 'WORLD_SIZE'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!`

I will take a look

2024-10-01 16:22 UTC, samsja commented on src/zeroband/train.py
> +    batch_size: int = 10
does this reffer to the training batch size or to something specific to the Monitor ? 

if it is the seconds then we need to rename as its confusing with the real batch size

2024-10-01 16:22 UTC, samsja commented on src/zeroband/utils/monitor.py
> +        self.batch_size = config["monitor"]["batch_size"] or 10
I don't think we need a default value (10) since we have the MonitorConfig now

2024-10-01 18:18 UTC, manveerxyz commented on src/zeroband/train.py
> +    batch_size: int = 10
renamed to `log_flush_interval`

2024-10-01 18:19 UTC, manveerxyz commented
okay, resolved changes + added `ip_address` logging since we need this for the map visualization on dashboard.

2024-10-03 20:21 UTC, samsja commented on configs/150M/3090.toml
> +metric_logger_type = "dummy"
lets remove this one from 3090.toml

2024-10-03 20:22 UTC, samsja commented on src/zeroband/train.py
> +    monitor: MonitorConfig = MonitorConfig()
```suggestion
    monitor: MonitorConfig | None = None
```

2024-10-03 20:22 UTC, samsja commented on src/zeroband/train.py
> +    enable_monitor: bool = False
```suggestion
```

lets use the None value for when its disabled

2024-10-03 20:24 UTC, samsja commented on src/zeroband/train.py
> +        monitor.set_stage("init")
```suggestion
        if config.monitor is not None:
              monitor = HttpMonitor(config=config.model_dump(), resume=False)
              monitor.set_stage("init")
```

2024-10-03 20:24 UTC, samsja commented on src/zeroband/train.py
> +            monitor.set_stage("inner_loop")
```suggestion
            if config.monitor is not None:
                 monitor.set_stage("inner_loop")
```

2024-10-03 20:25 UTC, samsja commented on src/zeroband/train.py
> +                monitor.log(metrics)
```suggestion
                if config.monitor is not None:
                     monitor.log(metrics)
```

2024-10-03 20:25 UTC, samsja commented on src/zeroband/train.py
> +                monitor.set_stage("outer_loop")
```suggestion
                if config.monitor is not None:
                     monitor.set_stage("outer_loop")
```

2024-10-03 20:26 UTC, samsja commented on src/zeroband/train.py
> +        monitor.finish()
```suggestion

        if config.monitor is not None:
              monitor.finish()
```

2024-10-03 20:27 UTC, samsja reviewed
added some tiny comments sorry

2024-10-04 18:15 UTC, samsja approved these changes
lfgtm !

2024-10-04 21:51 UTC, samsja commented
test are passing locally so I will merge the pr

2024-10-04 21:51 UTC, merged