use shared function for log model hash
PrimeIntellect-ai/prime-diloco pull request #179
Opened 2024-12-19 05:40 UTC by samsja

2024-12-19 20:07 UTC, Jackmin801 requested changes
Nice! Why are we killing GPU memory monitor though?

2024-12-19 20:07 UTC, Jackmin801 commented on src/zeroband/train.py
> +    math_attn: bool = False  # slow
What do you think about putting this as an option in `attn_fn` instead?

2024-12-19 20:07 UTC, Jackmin801 commented on src/zeroband/train.py
> +        math_attn=config.train.math_attn,
What do you think about passing attn_fn instead? Would also allow sdpa to be specified

2024-12-20 07:39 UTC, samsja commented on src/zeroband/train.py
> +    math_attn: bool = False  # slow
```
    attn_fn: Literal["flash", "sdpa"] | None = None

    @model_validator(mode="after")
    def validate_attn_fn(self):
        if self.attn_fn is not None:
            warnings.warn("attn_fn argument is deprecated")

        return self
```

hmm attn_fn is not used anymore. I just kept it to avoid conflict with old code.

2024-12-20 07:40 UTC, samsja commented
> Nice! Why are we killing GPU memory monitor though?

the profiler is enough I think

2024-12-20 08:24 UTC, samsja commented on src/zeroband/train.py
> +    math_attn: bool = False  # slow
pr to remove attn_fn https://github.com/PrimeIntellect-ai/prime/pull/180

2024-12-21 00:49 UTC, Jackmin801 commented
yea never used it either haha

2024-12-23 04:54 UTC, merged