remove deprecated attn_fn
PrimeIntellect-ai/prime-diloco pull request #180
Opened 2024-12-20 08:23 UTC by samsja

2024-12-21 00:52 UTC, Jackmin801 commented
If its not too hard to recall, why did we deprecate this?
What do you think about undeprecating it? I think it can be pretty useful to swap attn impls so id prefer to keep it

2024-12-21 00:52 UTC, Jackmin801 requested changes
Hrmm I dont think we should deprecate this

2024-12-23 04:56 UTC, samsja commented
> If its not too hard to recall, why did we deprecate this? What do you think about undeprecating it? I think it can be pretty useful to swap attn impls so id prefer to keep it

as of today we only have flex_attention or sdpa. The flash attention one has been removed. To dispatch to flex or sdpa is based on the `sequence_pakcing` parameters

2025-01-05 11:14 UTC, samsja commented
closing as we decided to use this flag

2025-01-06 20:06 UTC, closed without merging