feat fsdp2 diloco
PrimeIntellect-ai/prime-diloco pull request #53
Opened 2024-10-07 06:35 UTC by samsja

2024-10-07 07:21 UTC, Jackmin801 commented on src/zeroband/diloco.py
> +            param_offloaded.grad.to_local().copy_(grad)
ooh with this the retry logic is quite easy now right? We clone the grad before the reduce. try except and reclone if fail. I guess we always couldve done it but its more obvious now that grad is local haha

2024-10-07 07:28 UTC, Jackmin801 approved these changes
Looks great! LFG

2024-10-07 07:28 UTC, Jackmin801 commented on src/zeroband/train.py
> +    elastic_device_mesh = ElasticDeviceMesh("nccl")
hrmm I wonder if this makes CPU mesh DTensor ops use nccl instead of gloo. We never do any ops that would require the DTensor hooks in our code atm so its not tested

2024-10-07 07:40 UTC, samsja commented on src/zeroband/train.py
> +    elastic_device_mesh = ElasticDeviceMesh("nccl")
will remove it and test then

2024-10-07 08:03 UTC, samsja commented on src/zeroband/train.py
> +    elastic_device_mesh = ElasticDeviceMesh("nccl")
tested

2024-10-07 08:03 UTC, Jackmin801 requested changes

2024-10-07 08:03 UTC, Jackmin801 commented on src/zeroband/diloco.py
> +                    break
Hrmm we need to clone before the reduce in order for the retry to work. The all-reduce is performed in-place so the values are stale if it aborts mid-way.

If we keep a clone outside which is used to restore in the event of retry then it should be correct.

2024-10-07 08:18 UTC, samsja commented on src/zeroband/diloco.py
> +                    break
its doing clone already

2024-10-07 08:18 UTC, Jackmin801 commented on src/zeroband/diloco.py
> +                    break
yea missed the recalc. all good then!

2024-10-08 02:20 UTC, Jackmin801 approved these changes
lgtm!

2024-10-08 08:43 UTC, closed without merging